name: ai-compoiso - Frontend Image
run-name: ai-compoiso - Frontend Image - ${{ github.run_number }} 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm i

      - name: Build frontend
        run: |
          npm run build

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/funy-z/ai-compoiso-frontend:latest -f ./Dockerfile .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: funy-z
          password: ${{ secrets.ORG_PAT_V2 }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          echo ${{ secrets.ORG_PAT_V2 }}
          docker push ghcr.io/funy-z/ai-compoiso-frontend:latest

      - name: Send Webhook Notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "success", "data": { "repository_name": "ai-compoiso-frontend", "image_name": "ghcr.io/funy-z/ai-compoiso-frontend:latest" }}' \
            http://8.134.8.134:9081/webhook_github_action
